server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: api-user
          uri: lb://api-user
          predicates:
            - Path=/user/**

        - id: api-search
          uri: lb://api-search
          predicates:
            - Path=/search/**


