server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://10.10.10.10:3306/qp
    driver-class-name: org.mariadb.jdbc.Driver
    username: qp
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace